[package]
name = "netmon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.30.5"
tokio = { version = "1.36.0", features = ["net"] }
tokio-tungstenite = "0.21.0"
tui = "0.19.0"
